#! /bin/bash

rsync -az -e ssh --delete --exclude "_*" --exclude "config.rb" --exclude "upload" --exclude ".sass-cache" --exclude ".gitignore" --exclude ".git" --exclude ".DS_Store" . mikedeck@seemacrun.net:~/seemacrun.net/wp-content/themes/jens-theme/